- name: "Demonstrate connecting to switches"
  hosts: all
  gather_facts: no

  tasks:
    ###
    # Collect data
    ##
    - name: Gather facts (ops)
      ios_facts:
      when: ansible_network_os == 'ios'

    ###
    # Demonstrate variables
    #
    - name: Display facts
      debug:
        msg: "Hostname: {{ ansible_net_hostname }} 
              OS: {{ ansible_net_version }}
              Version: {{ hostvars[host].ansible_net_version }}
              Model: Model: {{ hostvars[host].ansible_net_model }}
              Serial: {{ hostvars[host].ansible_net_serialnum }}"
   
